	//------------------------------------------------------------------------------
	// <auto-generated>
	//     此代码由T4 Toolbox工具生成。
	//     对此文件的更改可能会导致不正确的行为，并且如果
	//     重新生成代码，这些更改将会丢失。
	//        如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现 RoleInfo分部方法（partial）。
	// </auto-generated>
	//
	// <copyright file="IRoleInfoDAL.generated.cs">
	//  
	//        所属工程：YwkManage.OA 中西医薛思源
	//        生成时间：2017-08-15 19:56
	// </copyright>
	//------------------------------------------------------------------------------

	using YwkManage.OA.Model;

	namespace YwkManage.OA.IDal
	{
		/// <summary>
		/// 数据层接口IDAL-数据表映射——RoleInfo
		/// </summary>    
		public partial interface IRoleInfoDal :IBaseDal<RoleInfo>
		{
		   
		}
	}
	